from edx_platform.cms.djangoapps.contentstore.views.component import *
from edx_platform.cms.djangoapps.contentstore.views.component import ADVANCED_COMPONENT_TYPES, CONTAINER_TEMPLATES, get_component_templates
ADVANCED_COMPONENT_TYPES = ADVANCED_COMPONENT_TYPES
CONTAINER_TEMPLATES=CONTAINER_TEMPLATES
get_component_templates = get_component_templates


